### ISSUE TITLE
 Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by 1337haxx0r** [Efim-Maisak/family-tree-dTree#1]
Issue with getting tree displayed:

I have setup Pocketbase with few entries, and I can see console.log() shows data I have inserted, but actual UI shows error.
See Image below:

![image](https://github.com/user-attachments/assets/141a2770-5105-4c69-8062-b5c746d330d4)

**Comment by Efim-Maisak** [comment]
> Issue with getting tree displayed:
> 
> I have setup Pocketbase with few entries, and I can see console.log() shows data I have inserted, but actual UI shows error. See Image below:

Check if you have set "key_node = true" for the most distant ancestor from the main tree.
And can you show me a full array of objects coming from the database?

PS: The project is in the development stage and is still raw, there may be bugs.

**Comment by 1337haxx0r** [comment]
> > Issue with getting tree displayed:
> > I have setup Pocketbase with few entries, and I can see console.log() shows data I have inserted, but actual UI shows error. See Image below:
> 
> Check if you have set "key_node = true" for the most distant ancestor from the main tree. And can you show me a full array of objects coming from the database?
> 
> PS: The project is in the development stage and is still raw, there may be bugs.


Yup.... I did have "false" on key_node. =) I put it to "true" it has been fixed. 
Appreciate your reply!
